[package]
name = "coordy"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "coordy"
path = "src/main.rs"

[dependencies]
coordy-local-runtime.workspace = true
coordy-protocol.workspace = true
clap.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
