export const IPC = {
  submit: "coordy:submit",
  view: "coordy:view",
  subscribe: "coordy:subscribe",
  effect: "coordy:effect",
  chooseRepository: "coordy:choose-repository",
  revealFile: "coordy:reveal-file",
  openTerminal: "coordy:open-terminal",
  getAppInfo: "coordy:get-app-info",
  installCli: "coordy:install-cli",
  secretsStatus: "coordy:secrets-status",
  setSecret: "coordy:set-secret",
  clearSecret: "coordy:clear-secret",
  completeDraft: "coordy:complete-draft",
  discoverAgents: "coordy:discover-agents",
  importAgents: "coordy:import-agents",
  listDirectory: "coordy:list-directory",
  quit: "coordy:quit",
} as const;
